USE [master]
GO
/****** Object:  Database [StarElectronicsDB]    Script Date: 18/08/2025 3:07:23 pm ******/
CREATE DATABASE [StarElectronicsDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'StarElectronicsDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER2022\MSSQL\DATA\StarElectronicsDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'StarElectronicsDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER2022\MSSQL\DATA\StarElectronicsDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [StarElectronicsDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [StarElectronicsDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [StarElectronicsDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [StarElectronicsDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [StarElectronicsDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [StarElectronicsDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [StarElectronicsDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [StarElectronicsDB] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [StarElectronicsDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [StarElectronicsDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [StarElectronicsDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [StarElectronicsDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [StarElectronicsDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [StarElectronicsDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [StarElectronicsDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [StarElectronicsDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [StarElectronicsDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [StarElectronicsDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [StarElectronicsDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [StarElectronicsDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [StarElectronicsDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [StarElectronicsDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [StarElectronicsDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [StarElectronicsDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [StarElectronicsDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [StarElectronicsDB] SET  MULTI_USER 
GO
ALTER DATABASE [StarElectronicsDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [StarElectronicsDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [StarElectronicsDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [StarElectronicsDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [StarElectronicsDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [StarElectronicsDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [StarElectronicsDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [StarElectronicsDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [StarElectronicsDB]
GO
/****** Object:  Table [dbo].[Products]    Script Date: 18/08/2025 3:07:24 pm ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Products](
	[ProductID] [int] IDENTITY(1,1) NOT NULL,
	[ProductName] [nvarchar](200) NOT NULL,
	[Category] [nvarchar](100) NULL,
	[Quantity] [int] NOT NULL,
	[PurchasePrice] [decimal](10, 2) NULL,
	[SalePrice] [decimal](10, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[ProductID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Purchases]    Script Date: 18/08/2025 3:07:25 pm ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Purchases](
	[PurchaseID] [int] IDENTITY(1,1) NOT NULL,
	[ProductID] [int] NOT NULL,
	[QuantityPurchased] [int] NOT NULL,
	[PurchaseDate] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[PurchaseID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Sales]    Script Date: 18/08/2025 3:07:25 pm ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Sales](
	[SaleID] [int] IDENTITY(1,1) NOT NULL,
	[ProductID] [int] NOT NULL,
	[QuantitySold] [int] NOT NULL,
	[SaleDate] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[SaleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Products] ADD  DEFAULT ((0)) FOR [Quantity]
GO
ALTER TABLE [dbo].[Purchases] ADD  DEFAULT (getdate()) FOR [PurchaseDate]
GO
ALTER TABLE [dbo].[Sales] ADD  DEFAULT (getdate()) FOR [SaleDate]
GO
ALTER TABLE [dbo].[Purchases]  WITH CHECK ADD FOREIGN KEY([ProductID])
REFERENCES [dbo].[Products] ([ProductID])
GO
ALTER TABLE [dbo].[Sales]  WITH CHECK ADD FOREIGN KEY([ProductID])
REFERENCES [dbo].[Products] ([ProductID])
GO
USE [master]
GO
ALTER DATABASE [StarElectronicsDB] SET  READ_WRITE 
GO
